/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: components/chromecast_controller/chromecast_protobuf/authority_keys.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "chromecast_protobuf/authority_keys.pb-c.h"
void   extensions__api__cast_channel__proto__authority_keys__key__init
                     (Extensions__Api__CastChannel__Proto__AuthorityKeys__Key         *message)
{
  static const Extensions__Api__CastChannel__Proto__AuthorityKeys__Key init_value = EXTENSIONS__API__CAST_CHANNEL__PROTO__AUTHORITY_KEYS__KEY__INIT;
  *message = init_value;
}
void   extensions__api__cast_channel__proto__authority_keys__init
                     (Extensions__Api__CastChannel__Proto__AuthorityKeys         *message)
{
  static const Extensions__Api__CastChannel__Proto__AuthorityKeys init_value = EXTENSIONS__API__CAST_CHANNEL__PROTO__AUTHORITY_KEYS__INIT;
  *message = init_value;
}
size_t extensions__api__cast_channel__proto__authority_keys__get_packed_size
                     (const Extensions__Api__CastChannel__Proto__AuthorityKeys *message)
{
  assert(message->base.descriptor == &extensions__api__cast_channel__proto__authority_keys__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t extensions__api__cast_channel__proto__authority_keys__pack
                     (const Extensions__Api__CastChannel__Proto__AuthorityKeys *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &extensions__api__cast_channel__proto__authority_keys__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t extensions__api__cast_channel__proto__authority_keys__pack_to_buffer
                     (const Extensions__Api__CastChannel__Proto__AuthorityKeys *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &extensions__api__cast_channel__proto__authority_keys__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Extensions__Api__CastChannel__Proto__AuthorityKeys *
       extensions__api__cast_channel__proto__authority_keys__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Extensions__Api__CastChannel__Proto__AuthorityKeys *)
     protobuf_c_message_unpack (&extensions__api__cast_channel__proto__authority_keys__descriptor,
                                allocator, len, data);
}
void   extensions__api__cast_channel__proto__authority_keys__free_unpacked
                     (Extensions__Api__CastChannel__Proto__AuthorityKeys *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &extensions__api__cast_channel__proto__authority_keys__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor extensions__api__cast_channel__proto__authority_keys__key__field_descriptors[2] =
{
  {
    "fingerprint",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Extensions__Api__CastChannel__Proto__AuthorityKeys__Key, fingerprint),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "public_key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Extensions__Api__CastChannel__Proto__AuthorityKeys__Key, public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned extensions__api__cast_channel__proto__authority_keys__key__field_indices_by_name[] = {
  0,   /* field[0] = fingerprint */
  1,   /* field[1] = public_key */
};
static const ProtobufCIntRange extensions__api__cast_channel__proto__authority_keys__key__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor extensions__api__cast_channel__proto__authority_keys__key__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "extensions.api.cast_channel.proto.AuthorityKeys.Key",
  "Key",
  "Extensions__Api__CastChannel__Proto__AuthorityKeys__Key",
  "extensions.api.cast_channel.proto",
  sizeof(Extensions__Api__CastChannel__Proto__AuthorityKeys__Key),
  2,
  extensions__api__cast_channel__proto__authority_keys__key__field_descriptors,
  extensions__api__cast_channel__proto__authority_keys__key__field_indices_by_name,
  1,  extensions__api__cast_channel__proto__authority_keys__key__number_ranges,
  (ProtobufCMessageInit) extensions__api__cast_channel__proto__authority_keys__key__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor extensions__api__cast_channel__proto__authority_keys__field_descriptors[1] =
{
  {
    "keys",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Extensions__Api__CastChannel__Proto__AuthorityKeys, n_keys),
    offsetof(Extensions__Api__CastChannel__Proto__AuthorityKeys, keys),
    &extensions__api__cast_channel__proto__authority_keys__key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned extensions__api__cast_channel__proto__authority_keys__field_indices_by_name[] = {
  0,   /* field[0] = keys */
};
static const ProtobufCIntRange extensions__api__cast_channel__proto__authority_keys__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor extensions__api__cast_channel__proto__authority_keys__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "extensions.api.cast_channel.proto.AuthorityKeys",
  "AuthorityKeys",
  "Extensions__Api__CastChannel__Proto__AuthorityKeys",
  "extensions.api.cast_channel.proto",
  sizeof(Extensions__Api__CastChannel__Proto__AuthorityKeys),
  1,
  extensions__api__cast_channel__proto__authority_keys__field_descriptors,
  extensions__api__cast_channel__proto__authority_keys__field_indices_by_name,
  1,  extensions__api__cast_channel__proto__authority_keys__number_ranges,
  (ProtobufCMessageInit) extensions__api__cast_channel__proto__authority_keys__init,
  NULL,NULL,NULL    /* reserved[123] */
};
