/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: components/chromecast_controller/chromecast_protobuf/authority_keys.proto */

#ifndef PROTOBUF_C_components_2fchromecast_5fcontroller_2fchromecast_5fprotobuf_2fauthority_5fkeys_2eproto__INCLUDED
#define PROTOBUF_C_components_2fchromecast_5fcontroller_2fchromecast_5fprotobuf_2fauthority_5fkeys_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Extensions__Api__CastChannel__Proto__AuthorityKeys Extensions__Api__CastChannel__Proto__AuthorityKeys;
typedef struct _Extensions__Api__CastChannel__Proto__AuthorityKeys__Key Extensions__Api__CastChannel__Proto__AuthorityKeys__Key;


/* --- enums --- */


/* --- messages --- */

struct  _Extensions__Api__CastChannel__Proto__AuthorityKeys__Key
{
  ProtobufCMessage base;
  ProtobufCBinaryData fingerprint;
  ProtobufCBinaryData public_key;
};
#define EXTENSIONS__API__CAST_CHANNEL__PROTO__AUTHORITY_KEYS__KEY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&extensions__api__cast_channel__proto__authority_keys__key__descriptor) \
    , {0,NULL}, {0,NULL} }


struct  _Extensions__Api__CastChannel__Proto__AuthorityKeys
{
  ProtobufCMessage base;
  size_t n_keys;
  Extensions__Api__CastChannel__Proto__AuthorityKeys__Key **keys;
};
#define EXTENSIONS__API__CAST_CHANNEL__PROTO__AUTHORITY_KEYS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&extensions__api__cast_channel__proto__authority_keys__descriptor) \
    , 0,NULL }


/* Extensions__Api__CastChannel__Proto__AuthorityKeys__Key methods */
void   extensions__api__cast_channel__proto__authority_keys__key__init
                     (Extensions__Api__CastChannel__Proto__AuthorityKeys__Key         *message);
/* Extensions__Api__CastChannel__Proto__AuthorityKeys methods */
void   extensions__api__cast_channel__proto__authority_keys__init
                     (Extensions__Api__CastChannel__Proto__AuthorityKeys         *message);
size_t extensions__api__cast_channel__proto__authority_keys__get_packed_size
                     (const Extensions__Api__CastChannel__Proto__AuthorityKeys   *message);
size_t extensions__api__cast_channel__proto__authority_keys__pack
                     (const Extensions__Api__CastChannel__Proto__AuthorityKeys   *message,
                      uint8_t             *out);
size_t extensions__api__cast_channel__proto__authority_keys__pack_to_buffer
                     (const Extensions__Api__CastChannel__Proto__AuthorityKeys   *message,
                      ProtobufCBuffer     *buffer);
Extensions__Api__CastChannel__Proto__AuthorityKeys *
       extensions__api__cast_channel__proto__authority_keys__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   extensions__api__cast_channel__proto__authority_keys__free_unpacked
                     (Extensions__Api__CastChannel__Proto__AuthorityKeys *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Extensions__Api__CastChannel__Proto__AuthorityKeys__Key_Closure)
                 (const Extensions__Api__CastChannel__Proto__AuthorityKeys__Key *message,
                  void *closure_data);
typedef void (*Extensions__Api__CastChannel__Proto__AuthorityKeys_Closure)
                 (const Extensions__Api__CastChannel__Proto__AuthorityKeys *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor extensions__api__cast_channel__proto__authority_keys__descriptor;
extern const ProtobufCMessageDescriptor extensions__api__cast_channel__proto__authority_keys__key__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_components_2fchromecast_5fcontroller_2fchromecast_5fprotobuf_2fauthority_5fkeys_2eproto__INCLUDED */
