/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: components/chromecast_controller/chromecast_protobuf/logging.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "chromecast_protobuf/logging.pb-c.h"
void   extensions__api__cast_channel__proto__socket_event__init
                     (Extensions__Api__CastChannel__Proto__SocketEvent         *message)
{
  static const Extensions__Api__CastChannel__Proto__SocketEvent init_value = EXTENSIONS__API__CAST_CHANNEL__PROTO__SOCKET_EVENT__INIT;
  *message = init_value;
}
size_t extensions__api__cast_channel__proto__socket_event__get_packed_size
                     (const Extensions__Api__CastChannel__Proto__SocketEvent *message)
{
  assert(message->base.descriptor == &extensions__api__cast_channel__proto__socket_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t extensions__api__cast_channel__proto__socket_event__pack
                     (const Extensions__Api__CastChannel__Proto__SocketEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &extensions__api__cast_channel__proto__socket_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t extensions__api__cast_channel__proto__socket_event__pack_to_buffer
                     (const Extensions__Api__CastChannel__Proto__SocketEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &extensions__api__cast_channel__proto__socket_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Extensions__Api__CastChannel__Proto__SocketEvent *
       extensions__api__cast_channel__proto__socket_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Extensions__Api__CastChannel__Proto__SocketEvent *)
     protobuf_c_message_unpack (&extensions__api__cast_channel__proto__socket_event__descriptor,
                                allocator, len, data);
}
void   extensions__api__cast_channel__proto__socket_event__free_unpacked
                     (Extensions__Api__CastChannel__Proto__SocketEvent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &extensions__api__cast_channel__proto__socket_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   extensions__api__cast_channel__proto__aggregated_socket_event__init
                     (Extensions__Api__CastChannel__Proto__AggregatedSocketEvent         *message)
{
  static const Extensions__Api__CastChannel__Proto__AggregatedSocketEvent init_value = EXTENSIONS__API__CAST_CHANNEL__PROTO__AGGREGATED_SOCKET_EVENT__INIT;
  *message = init_value;
}
size_t extensions__api__cast_channel__proto__aggregated_socket_event__get_packed_size
                     (const Extensions__Api__CastChannel__Proto__AggregatedSocketEvent *message)
{
  assert(message->base.descriptor == &extensions__api__cast_channel__proto__aggregated_socket_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t extensions__api__cast_channel__proto__aggregated_socket_event__pack
                     (const Extensions__Api__CastChannel__Proto__AggregatedSocketEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &extensions__api__cast_channel__proto__aggregated_socket_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t extensions__api__cast_channel__proto__aggregated_socket_event__pack_to_buffer
                     (const Extensions__Api__CastChannel__Proto__AggregatedSocketEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &extensions__api__cast_channel__proto__aggregated_socket_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Extensions__Api__CastChannel__Proto__AggregatedSocketEvent *
       extensions__api__cast_channel__proto__aggregated_socket_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Extensions__Api__CastChannel__Proto__AggregatedSocketEvent *)
     protobuf_c_message_unpack (&extensions__api__cast_channel__proto__aggregated_socket_event__descriptor,
                                allocator, len, data);
}
void   extensions__api__cast_channel__proto__aggregated_socket_event__free_unpacked
                     (Extensions__Api__CastChannel__Proto__AggregatedSocketEvent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &extensions__api__cast_channel__proto__aggregated_socket_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   extensions__api__cast_channel__proto__log__init
                     (Extensions__Api__CastChannel__Proto__Log         *message)
{
  static const Extensions__Api__CastChannel__Proto__Log init_value = EXTENSIONS__API__CAST_CHANNEL__PROTO__LOG__INIT;
  *message = init_value;
}
size_t extensions__api__cast_channel__proto__log__get_packed_size
                     (const Extensions__Api__CastChannel__Proto__Log *message)
{
  assert(message->base.descriptor == &extensions__api__cast_channel__proto__log__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t extensions__api__cast_channel__proto__log__pack
                     (const Extensions__Api__CastChannel__Proto__Log *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &extensions__api__cast_channel__proto__log__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t extensions__api__cast_channel__proto__log__pack_to_buffer
                     (const Extensions__Api__CastChannel__Proto__Log *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &extensions__api__cast_channel__proto__log__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Extensions__Api__CastChannel__Proto__Log *
       extensions__api__cast_channel__proto__log__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Extensions__Api__CastChannel__Proto__Log *)
     protobuf_c_message_unpack (&extensions__api__cast_channel__proto__log__descriptor,
                                allocator, len, data);
}
void   extensions__api__cast_channel__proto__log__free_unpacked
                     (Extensions__Api__CastChannel__Proto__Log *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &extensions__api__cast_channel__proto__log__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor extensions__api__cast_channel__proto__socket_event__field_descriptors[12] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, has_type),
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, type),
    &extensions__api__cast_channel__proto__event_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp_micros",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, has_timestamp_micros),
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, timestamp_micros),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "details",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, details),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "net_return_value",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, has_net_return_value),
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, net_return_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_namespace",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, message_namespace),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ready_state",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, has_ready_state),
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, ready_state),
    &extensions__api__cast_channel__proto__ready_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connection_state",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, has_connection_state),
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, connection_state),
    &extensions__api__cast_channel__proto__connection_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read_state",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, has_read_state),
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, read_state),
    &extensions__api__cast_channel__proto__read_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "write_state",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, has_write_state),
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, write_state),
    &extensions__api__cast_channel__proto__write_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_state",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, has_error_state),
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, error_state),
    &extensions__api__cast_channel__proto__error_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "challenge_reply_error_type",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, has_challenge_reply_error_type),
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, challenge_reply_error_type),
    &extensions__api__cast_channel__proto__challenge_reply_error_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nss_error_code",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, has_nss_error_code),
    offsetof(Extensions__Api__CastChannel__Proto__SocketEvent, nss_error_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned extensions__api__cast_channel__proto__socket_event__field_indices_by_name[] = {
  10,   /* field[10] = challenge_reply_error_type */
  6,   /* field[6] = connection_state */
  2,   /* field[2] = details */
  9,   /* field[9] = error_state */
  4,   /* field[4] = message_namespace */
  3,   /* field[3] = net_return_value */
  11,   /* field[11] = nss_error_code */
  7,   /* field[7] = read_state */
  5,   /* field[5] = ready_state */
  1,   /* field[1] = timestamp_micros */
  0,   /* field[0] = type */
  8,   /* field[8] = write_state */
};
static const ProtobufCIntRange extensions__api__cast_channel__proto__socket_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor extensions__api__cast_channel__proto__socket_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "extensions.api.cast_channel.proto.SocketEvent",
  "SocketEvent",
  "Extensions__Api__CastChannel__Proto__SocketEvent",
  "extensions.api.cast_channel.proto",
  sizeof(Extensions__Api__CastChannel__Proto__SocketEvent),
  12,
  extensions__api__cast_channel__proto__socket_event__field_descriptors,
  extensions__api__cast_channel__proto__socket_event__field_indices_by_name,
  1,  extensions__api__cast_channel__proto__socket_event__number_ranges,
  (ProtobufCMessageInit) extensions__api__cast_channel__proto__socket_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor extensions__api__cast_channel__proto__aggregated_socket_event__field_descriptors[6] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Extensions__Api__CastChannel__Proto__AggregatedSocketEvent, has_id),
    offsetof(Extensions__Api__CastChannel__Proto__AggregatedSocketEvent, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "endpoint_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Extensions__Api__CastChannel__Proto__AggregatedSocketEvent, has_endpoint_id),
    offsetof(Extensions__Api__CastChannel__Proto__AggregatedSocketEvent, endpoint_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel_auth_type",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Extensions__Api__CastChannel__Proto__AggregatedSocketEvent, has_channel_auth_type),
    offsetof(Extensions__Api__CastChannel__Proto__AggregatedSocketEvent, channel_auth_type),
    &extensions__api__cast_channel__proto__channel_auth__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "socket_event",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Extensions__Api__CastChannel__Proto__AggregatedSocketEvent, n_socket_event),
    offsetof(Extensions__Api__CastChannel__Proto__AggregatedSocketEvent, socket_event),
    &extensions__api__cast_channel__proto__socket_event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bytes_read",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Extensions__Api__CastChannel__Proto__AggregatedSocketEvent, has_bytes_read),
    offsetof(Extensions__Api__CastChannel__Proto__AggregatedSocketEvent, bytes_read),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bytes_written",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Extensions__Api__CastChannel__Proto__AggregatedSocketEvent, has_bytes_written),
    offsetof(Extensions__Api__CastChannel__Proto__AggregatedSocketEvent, bytes_written),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned extensions__api__cast_channel__proto__aggregated_socket_event__field_indices_by_name[] = {
  4,   /* field[4] = bytes_read */
  5,   /* field[5] = bytes_written */
  2,   /* field[2] = channel_auth_type */
  1,   /* field[1] = endpoint_id */
  0,   /* field[0] = id */
  3,   /* field[3] = socket_event */
};
static const ProtobufCIntRange extensions__api__cast_channel__proto__aggregated_socket_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor extensions__api__cast_channel__proto__aggregated_socket_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "extensions.api.cast_channel.proto.AggregatedSocketEvent",
  "AggregatedSocketEvent",
  "Extensions__Api__CastChannel__Proto__AggregatedSocketEvent",
  "extensions.api.cast_channel.proto",
  sizeof(Extensions__Api__CastChannel__Proto__AggregatedSocketEvent),
  6,
  extensions__api__cast_channel__proto__aggregated_socket_event__field_descriptors,
  extensions__api__cast_channel__proto__aggregated_socket_event__field_indices_by_name,
  1,  extensions__api__cast_channel__proto__aggregated_socket_event__number_ranges,
  (ProtobufCMessageInit) extensions__api__cast_channel__proto__aggregated_socket_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor extensions__api__cast_channel__proto__log__field_descriptors[3] =
{
  {
    "aggregated_socket_event",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Extensions__Api__CastChannel__Proto__Log, n_aggregated_socket_event),
    offsetof(Extensions__Api__CastChannel__Proto__Log, aggregated_socket_event),
    &extensions__api__cast_channel__proto__aggregated_socket_event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_evicted_aggregated_socket_events",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Extensions__Api__CastChannel__Proto__Log, has_num_evicted_aggregated_socket_events),
    offsetof(Extensions__Api__CastChannel__Proto__Log, num_evicted_aggregated_socket_events),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_evicted_socket_events",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Extensions__Api__CastChannel__Proto__Log, has_num_evicted_socket_events),
    offsetof(Extensions__Api__CastChannel__Proto__Log, num_evicted_socket_events),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned extensions__api__cast_channel__proto__log__field_indices_by_name[] = {
  0,   /* field[0] = aggregated_socket_event */
  1,   /* field[1] = num_evicted_aggregated_socket_events */
  2,   /* field[2] = num_evicted_socket_events */
};
static const ProtobufCIntRange extensions__api__cast_channel__proto__log__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor extensions__api__cast_channel__proto__log__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "extensions.api.cast_channel.proto.Log",
  "Log",
  "Extensions__Api__CastChannel__Proto__Log",
  "extensions.api.cast_channel.proto",
  sizeof(Extensions__Api__CastChannel__Proto__Log),
  3,
  extensions__api__cast_channel__proto__log__field_descriptors,
  extensions__api__cast_channel__proto__log__field_indices_by_name,
  1,  extensions__api__cast_channel__proto__log__number_ranges,
  (ProtobufCMessageInit) extensions__api__cast_channel__proto__log__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue extensions__api__cast_channel__proto__event_type__enum_values_by_number[32] =
{
  { "EVENT_TYPE_UNKNOWN", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__EVENT_TYPE_UNKNOWN", 0 },
  { "CAST_SOCKET_CREATED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__CAST_SOCKET_CREATED", 1 },
  { "READY_STATE_CHANGED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__READY_STATE_CHANGED", 2 },
  { "CONNECTION_STATE_CHANGED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__CONNECTION_STATE_CHANGED", 3 },
  { "READ_STATE_CHANGED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__READ_STATE_CHANGED", 4 },
  { "WRITE_STATE_CHANGED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__WRITE_STATE_CHANGED", 5 },
  { "ERROR_STATE_CHANGED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__ERROR_STATE_CHANGED", 6 },
  { "CONNECT_FAILED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__CONNECT_FAILED", 7 },
  { "TCP_SOCKET_CONNECT", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__TCP_SOCKET_CONNECT", 8 },
  { "TCP_SOCKET_SET_KEEP_ALIVE", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__TCP_SOCKET_SET_KEEP_ALIVE", 9 },
  { "SSL_CERT_WHITELISTED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__SSL_CERT_WHITELISTED", 10 },
  { "SSL_SOCKET_CONNECT", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__SSL_SOCKET_CONNECT", 11 },
  { "SSL_INFO_OBTAINED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__SSL_INFO_OBTAINED", 12 },
  { "DER_ENCODED_CERT_OBTAIN", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__DER_ENCODED_CERT_OBTAIN", 13 },
  { "RECEIVED_CHALLENGE_REPLY", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__RECEIVED_CHALLENGE_REPLY", 14 },
  { "AUTH_CHALLENGE_REPLY", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__AUTH_CHALLENGE_REPLY", 15 },
  { "CONNECT_TIMED_OUT", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__CONNECT_TIMED_OUT", 16 },
  { "SEND_MESSAGE_FAILED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__SEND_MESSAGE_FAILED", 17 },
  { "MESSAGE_ENQUEUED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__MESSAGE_ENQUEUED", 18 },
  { "SOCKET_WRITE", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__SOCKET_WRITE", 19 },
  { "MESSAGE_WRITTEN", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__MESSAGE_WRITTEN", 20 },
  { "SOCKET_READ", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__SOCKET_READ", 21 },
  { "MESSAGE_READ", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__MESSAGE_READ", 22 },
  { "SOCKET_CLOSED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__SOCKET_CLOSED", 25 },
  { "SSL_CERT_EXCESSIVE_LIFETIME", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__SSL_CERT_EXCESSIVE_LIFETIME", 26 },
  { "CHANNEL_POLICY_ENFORCED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__CHANNEL_POLICY_ENFORCED", 27 },
  { "TCP_SOCKET_CONNECT_COMPLETE", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__TCP_SOCKET_CONNECT_COMPLETE", 28 },
  { "SSL_SOCKET_CONNECT_COMPLETE", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__SSL_SOCKET_CONNECT_COMPLETE", 29 },
  { "SSL_SOCKET_CONNECT_FAILED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__SSL_SOCKET_CONNECT_FAILED", 30 },
  { "SEND_AUTH_CHALLENGE_FAILED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__SEND_AUTH_CHALLENGE_FAILED", 31 },
  { "AUTH_CHALLENGE_REPLY_INVALID", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__AUTH_CHALLENGE_REPLY_INVALID", 32 },
  { "PING_WRITE_ERROR", "EXTENSIONS__API__CAST_CHANNEL__PROTO__EVENT_TYPE__PING_WRITE_ERROR", 33 },
};
static const ProtobufCIntRange extensions__api__cast_channel__proto__event_type__value_ranges[] = {
{0, 0},{25, 23},{0, 32}
};
static const ProtobufCEnumValueIndex extensions__api__cast_channel__proto__event_type__enum_values_by_name[32] =
{
  { "AUTH_CHALLENGE_REPLY", 15 },
  { "AUTH_CHALLENGE_REPLY_INVALID", 30 },
  { "CAST_SOCKET_CREATED", 1 },
  { "CHANNEL_POLICY_ENFORCED", 25 },
  { "CONNECTION_STATE_CHANGED", 3 },
  { "CONNECT_FAILED", 7 },
  { "CONNECT_TIMED_OUT", 16 },
  { "DER_ENCODED_CERT_OBTAIN", 13 },
  { "ERROR_STATE_CHANGED", 6 },
  { "EVENT_TYPE_UNKNOWN", 0 },
  { "MESSAGE_ENQUEUED", 18 },
  { "MESSAGE_READ", 22 },
  { "MESSAGE_WRITTEN", 20 },
  { "PING_WRITE_ERROR", 31 },
  { "READY_STATE_CHANGED", 2 },
  { "READ_STATE_CHANGED", 4 },
  { "RECEIVED_CHALLENGE_REPLY", 14 },
  { "SEND_AUTH_CHALLENGE_FAILED", 29 },
  { "SEND_MESSAGE_FAILED", 17 },
  { "SOCKET_CLOSED", 23 },
  { "SOCKET_READ", 21 },
  { "SOCKET_WRITE", 19 },
  { "SSL_CERT_EXCESSIVE_LIFETIME", 24 },
  { "SSL_CERT_WHITELISTED", 10 },
  { "SSL_INFO_OBTAINED", 12 },
  { "SSL_SOCKET_CONNECT", 11 },
  { "SSL_SOCKET_CONNECT_COMPLETE", 27 },
  { "SSL_SOCKET_CONNECT_FAILED", 28 },
  { "TCP_SOCKET_CONNECT", 8 },
  { "TCP_SOCKET_CONNECT_COMPLETE", 26 },
  { "TCP_SOCKET_SET_KEEP_ALIVE", 9 },
  { "WRITE_STATE_CHANGED", 5 },
};
const ProtobufCEnumDescriptor extensions__api__cast_channel__proto__event_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "extensions.api.cast_channel.proto.EventType",
  "EventType",
  "Extensions__Api__CastChannel__Proto__EventType",
  "extensions.api.cast_channel.proto",
  32,
  extensions__api__cast_channel__proto__event_type__enum_values_by_number,
  32,
  extensions__api__cast_channel__proto__event_type__enum_values_by_name,
  2,
  extensions__api__cast_channel__proto__event_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue extensions__api__cast_channel__proto__channel_auth__enum_values_by_number[2] =
{
  { "SSL", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CHANNEL_AUTH__SSL", 1 },
  { "SSL_VERIFIED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CHANNEL_AUTH__SSL_VERIFIED", 2 },
};
static const ProtobufCIntRange extensions__api__cast_channel__proto__channel_auth__value_ranges[] = {
{1, 0},{0, 2}
};
static const ProtobufCEnumValueIndex extensions__api__cast_channel__proto__channel_auth__enum_values_by_name[2] =
{
  { "SSL", 0 },
  { "SSL_VERIFIED", 1 },
};
const ProtobufCEnumDescriptor extensions__api__cast_channel__proto__channel_auth__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "extensions.api.cast_channel.proto.ChannelAuth",
  "ChannelAuth",
  "Extensions__Api__CastChannel__Proto__ChannelAuth",
  "extensions.api.cast_channel.proto",
  2,
  extensions__api__cast_channel__proto__channel_auth__enum_values_by_number,
  2,
  extensions__api__cast_channel__proto__channel_auth__enum_values_by_name,
  1,
  extensions__api__cast_channel__proto__channel_auth__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue extensions__api__cast_channel__proto__ready_state__enum_values_by_number[5] =
{
  { "READY_STATE_NONE", "EXTENSIONS__API__CAST_CHANNEL__PROTO__READY_STATE__READY_STATE_NONE", 1 },
  { "READY_STATE_CONNECTING", "EXTENSIONS__API__CAST_CHANNEL__PROTO__READY_STATE__READY_STATE_CONNECTING", 2 },
  { "READY_STATE_OPEN", "EXTENSIONS__API__CAST_CHANNEL__PROTO__READY_STATE__READY_STATE_OPEN", 3 },
  { "READY_STATE_CLOSING", "EXTENSIONS__API__CAST_CHANNEL__PROTO__READY_STATE__READY_STATE_CLOSING", 4 },
  { "READY_STATE_CLOSED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__READY_STATE__READY_STATE_CLOSED", 5 },
};
static const ProtobufCIntRange extensions__api__cast_channel__proto__ready_state__value_ranges[] = {
{1, 0},{0, 5}
};
static const ProtobufCEnumValueIndex extensions__api__cast_channel__proto__ready_state__enum_values_by_name[5] =
{
  { "READY_STATE_CLOSED", 4 },
  { "READY_STATE_CLOSING", 3 },
  { "READY_STATE_CONNECTING", 1 },
  { "READY_STATE_NONE", 0 },
  { "READY_STATE_OPEN", 2 },
};
const ProtobufCEnumDescriptor extensions__api__cast_channel__proto__ready_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "extensions.api.cast_channel.proto.ReadyState",
  "ReadyState",
  "Extensions__Api__CastChannel__Proto__ReadyState",
  "extensions.api.cast_channel.proto",
  5,
  extensions__api__cast_channel__proto__ready_state__enum_values_by_number,
  5,
  extensions__api__cast_channel__proto__ready_state__enum_values_by_name,
  1,
  extensions__api__cast_channel__proto__ready_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue extensions__api__cast_channel__proto__connection_state__enum_values_by_number[12] =
{
  { "CONN_STATE_UNKNOWN", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CONNECTION_STATE__CONN_STATE_UNKNOWN", 1 },
  { "CONN_STATE_TCP_CONNECT", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CONNECTION_STATE__CONN_STATE_TCP_CONNECT", 2 },
  { "CONN_STATE_TCP_CONNECT_COMPLETE", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CONNECTION_STATE__CONN_STATE_TCP_CONNECT_COMPLETE", 3 },
  { "CONN_STATE_SSL_CONNECT", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CONNECTION_STATE__CONN_STATE_SSL_CONNECT", 4 },
  { "CONN_STATE_SSL_CONNECT_COMPLETE", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CONNECTION_STATE__CONN_STATE_SSL_CONNECT_COMPLETE", 5 },
  { "CONN_STATE_AUTH_CHALLENGE_SEND", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CONNECTION_STATE__CONN_STATE_AUTH_CHALLENGE_SEND", 6 },
  { "CONN_STATE_AUTH_CHALLENGE_SEND_COMPLETE", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CONNECTION_STATE__CONN_STATE_AUTH_CHALLENGE_SEND_COMPLETE", 7 },
  { "CONN_STATE_AUTH_CHALLENGE_REPLY_COMPLETE", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CONNECTION_STATE__CONN_STATE_AUTH_CHALLENGE_REPLY_COMPLETE", 8 },
  { "CONN_STATE_START_CONNECT", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CONNECTION_STATE__CONN_STATE_START_CONNECT", 9 },
  { "CONN_STATE_FINISHED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CONNECTION_STATE__CONN_STATE_FINISHED", 100 },
  { "CONN_STATE_ERROR", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CONNECTION_STATE__CONN_STATE_ERROR", 101 },
  { "CONN_STATE_TIMEOUT", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CONNECTION_STATE__CONN_STATE_TIMEOUT", 102 },
};
static const ProtobufCIntRange extensions__api__cast_channel__proto__connection_state__value_ranges[] = {
{1, 0},{100, 9},{0, 12}
};
static const ProtobufCEnumValueIndex extensions__api__cast_channel__proto__connection_state__enum_values_by_name[12] =
{
  { "CONN_STATE_AUTH_CHALLENGE_REPLY_COMPLETE", 7 },
  { "CONN_STATE_AUTH_CHALLENGE_SEND", 5 },
  { "CONN_STATE_AUTH_CHALLENGE_SEND_COMPLETE", 6 },
  { "CONN_STATE_ERROR", 10 },
  { "CONN_STATE_FINISHED", 9 },
  { "CONN_STATE_SSL_CONNECT", 3 },
  { "CONN_STATE_SSL_CONNECT_COMPLETE", 4 },
  { "CONN_STATE_START_CONNECT", 8 },
  { "CONN_STATE_TCP_CONNECT", 1 },
  { "CONN_STATE_TCP_CONNECT_COMPLETE", 2 },
  { "CONN_STATE_TIMEOUT", 11 },
  { "CONN_STATE_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor extensions__api__cast_channel__proto__connection_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "extensions.api.cast_channel.proto.ConnectionState",
  "ConnectionState",
  "Extensions__Api__CastChannel__Proto__ConnectionState",
  "extensions.api.cast_channel.proto",
  12,
  extensions__api__cast_channel__proto__connection_state__enum_values_by_number,
  12,
  extensions__api__cast_channel__proto__connection_state__enum_values_by_name,
  2,
  extensions__api__cast_channel__proto__connection_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue extensions__api__cast_channel__proto__read_state__enum_values_by_number[6] =
{
  { "READ_STATE_UNKNOWN", "EXTENSIONS__API__CAST_CHANNEL__PROTO__READ_STATE__READ_STATE_UNKNOWN", 1 },
  { "READ_STATE_READ", "EXTENSIONS__API__CAST_CHANNEL__PROTO__READ_STATE__READ_STATE_READ", 2 },
  { "READ_STATE_READ_COMPLETE", "EXTENSIONS__API__CAST_CHANNEL__PROTO__READ_STATE__READ_STATE_READ_COMPLETE", 3 },
  { "READ_STATE_DO_CALLBACK", "EXTENSIONS__API__CAST_CHANNEL__PROTO__READ_STATE__READ_STATE_DO_CALLBACK", 4 },
  { "READ_STATE_HANDLE_ERROR", "EXTENSIONS__API__CAST_CHANNEL__PROTO__READ_STATE__READ_STATE_HANDLE_ERROR", 5 },
  { "READ_STATE_ERROR", "EXTENSIONS__API__CAST_CHANNEL__PROTO__READ_STATE__READ_STATE_ERROR", 100 },
};
static const ProtobufCIntRange extensions__api__cast_channel__proto__read_state__value_ranges[] = {
{1, 0},{100, 5},{0, 6}
};
static const ProtobufCEnumValueIndex extensions__api__cast_channel__proto__read_state__enum_values_by_name[6] =
{
  { "READ_STATE_DO_CALLBACK", 3 },
  { "READ_STATE_ERROR", 5 },
  { "READ_STATE_HANDLE_ERROR", 4 },
  { "READ_STATE_READ", 1 },
  { "READ_STATE_READ_COMPLETE", 2 },
  { "READ_STATE_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor extensions__api__cast_channel__proto__read_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "extensions.api.cast_channel.proto.ReadState",
  "ReadState",
  "Extensions__Api__CastChannel__Proto__ReadState",
  "extensions.api.cast_channel.proto",
  6,
  extensions__api__cast_channel__proto__read_state__enum_values_by_number,
  6,
  extensions__api__cast_channel__proto__read_state__enum_values_by_name,
  2,
  extensions__api__cast_channel__proto__read_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue extensions__api__cast_channel__proto__write_state__enum_values_by_number[7] =
{
  { "WRITE_STATE_UNKNOWN", "EXTENSIONS__API__CAST_CHANNEL__PROTO__WRITE_STATE__WRITE_STATE_UNKNOWN", 1 },
  { "WRITE_STATE_WRITE", "EXTENSIONS__API__CAST_CHANNEL__PROTO__WRITE_STATE__WRITE_STATE_WRITE", 2 },
  { "WRITE_STATE_WRITE_COMPLETE", "EXTENSIONS__API__CAST_CHANNEL__PROTO__WRITE_STATE__WRITE_STATE_WRITE_COMPLETE", 3 },
  { "WRITE_STATE_DO_CALLBACK", "EXTENSIONS__API__CAST_CHANNEL__PROTO__WRITE_STATE__WRITE_STATE_DO_CALLBACK", 4 },
  { "WRITE_STATE_HANDLE_ERROR", "EXTENSIONS__API__CAST_CHANNEL__PROTO__WRITE_STATE__WRITE_STATE_HANDLE_ERROR", 5 },
  { "WRITE_STATE_ERROR", "EXTENSIONS__API__CAST_CHANNEL__PROTO__WRITE_STATE__WRITE_STATE_ERROR", 100 },
  { "WRITE_STATE_IDLE", "EXTENSIONS__API__CAST_CHANNEL__PROTO__WRITE_STATE__WRITE_STATE_IDLE", 101 },
};
static const ProtobufCIntRange extensions__api__cast_channel__proto__write_state__value_ranges[] = {
{1, 0},{100, 5},{0, 7}
};
static const ProtobufCEnumValueIndex extensions__api__cast_channel__proto__write_state__enum_values_by_name[7] =
{
  { "WRITE_STATE_DO_CALLBACK", 3 },
  { "WRITE_STATE_ERROR", 5 },
  { "WRITE_STATE_HANDLE_ERROR", 4 },
  { "WRITE_STATE_IDLE", 6 },
  { "WRITE_STATE_UNKNOWN", 0 },
  { "WRITE_STATE_WRITE", 1 },
  { "WRITE_STATE_WRITE_COMPLETE", 2 },
};
const ProtobufCEnumDescriptor extensions__api__cast_channel__proto__write_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "extensions.api.cast_channel.proto.WriteState",
  "WriteState",
  "Extensions__Api__CastChannel__Proto__WriteState",
  "extensions.api.cast_channel.proto",
  7,
  extensions__api__cast_channel__proto__write_state__enum_values_by_number,
  7,
  extensions__api__cast_channel__proto__write_state__enum_values_by_name,
  2,
  extensions__api__cast_channel__proto__write_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue extensions__api__cast_channel__proto__error_state__enum_values_by_number[10] =
{
  { "CHANNEL_ERROR_NONE", "EXTENSIONS__API__CAST_CHANNEL__PROTO__ERROR_STATE__CHANNEL_ERROR_NONE", 1 },
  { "CHANNEL_ERROR_CHANNEL_NOT_OPEN", "EXTENSIONS__API__CAST_CHANNEL__PROTO__ERROR_STATE__CHANNEL_ERROR_CHANNEL_NOT_OPEN", 2 },
  { "CHANNEL_ERROR_AUTHENTICATION_ERROR", "EXTENSIONS__API__CAST_CHANNEL__PROTO__ERROR_STATE__CHANNEL_ERROR_AUTHENTICATION_ERROR", 3 },
  { "CHANNEL_ERROR_CONNECT_ERROR", "EXTENSIONS__API__CAST_CHANNEL__PROTO__ERROR_STATE__CHANNEL_ERROR_CONNECT_ERROR", 4 },
  { "CHANNEL_ERROR_SOCKET_ERROR", "EXTENSIONS__API__CAST_CHANNEL__PROTO__ERROR_STATE__CHANNEL_ERROR_SOCKET_ERROR", 5 },
  { "CHANNEL_ERROR_TRANSPORT_ERROR", "EXTENSIONS__API__CAST_CHANNEL__PROTO__ERROR_STATE__CHANNEL_ERROR_TRANSPORT_ERROR", 6 },
  { "CHANNEL_ERROR_INVALID_MESSAGE", "EXTENSIONS__API__CAST_CHANNEL__PROTO__ERROR_STATE__CHANNEL_ERROR_INVALID_MESSAGE", 7 },
  { "CHANNEL_ERROR_INVALID_CHANNEL_ID", "EXTENSIONS__API__CAST_CHANNEL__PROTO__ERROR_STATE__CHANNEL_ERROR_INVALID_CHANNEL_ID", 8 },
  { "CHANNEL_ERROR_CONNECT_TIMEOUT", "EXTENSIONS__API__CAST_CHANNEL__PROTO__ERROR_STATE__CHANNEL_ERROR_CONNECT_TIMEOUT", 9 },
  { "CHANNEL_ERROR_UNKNOWN", "EXTENSIONS__API__CAST_CHANNEL__PROTO__ERROR_STATE__CHANNEL_ERROR_UNKNOWN", 10 },
};
static const ProtobufCIntRange extensions__api__cast_channel__proto__error_state__value_ranges[] = {
{1, 0},{0, 10}
};
static const ProtobufCEnumValueIndex extensions__api__cast_channel__proto__error_state__enum_values_by_name[10] =
{
  { "CHANNEL_ERROR_AUTHENTICATION_ERROR", 2 },
  { "CHANNEL_ERROR_CHANNEL_NOT_OPEN", 1 },
  { "CHANNEL_ERROR_CONNECT_ERROR", 3 },
  { "CHANNEL_ERROR_CONNECT_TIMEOUT", 8 },
  { "CHANNEL_ERROR_INVALID_CHANNEL_ID", 7 },
  { "CHANNEL_ERROR_INVALID_MESSAGE", 6 },
  { "CHANNEL_ERROR_NONE", 0 },
  { "CHANNEL_ERROR_SOCKET_ERROR", 4 },
  { "CHANNEL_ERROR_TRANSPORT_ERROR", 5 },
  { "CHANNEL_ERROR_UNKNOWN", 9 },
};
const ProtobufCEnumDescriptor extensions__api__cast_channel__proto__error_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "extensions.api.cast_channel.proto.ErrorState",
  "ErrorState",
  "Extensions__Api__CastChannel__Proto__ErrorState",
  "extensions.api.cast_channel.proto",
  10,
  extensions__api__cast_channel__proto__error_state__enum_values_by_number,
  10,
  extensions__api__cast_channel__proto__error_state__enum_values_by_name,
  1,
  extensions__api__cast_channel__proto__error_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue extensions__api__cast_channel__proto__challenge_reply_error_type__enum_values_by_number[17] =
{
  { "CHALLENGE_REPLY_ERROR_NONE", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CHALLENGE_REPLY_ERROR_TYPE__CHALLENGE_REPLY_ERROR_NONE", 1 },
  { "CHALLENGE_REPLY_ERROR_PEER_CERT_EMPTY", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CHALLENGE_REPLY_ERROR_TYPE__CHALLENGE_REPLY_ERROR_PEER_CERT_EMPTY", 2 },
  { "CHALLENGE_REPLY_ERROR_WRONG_PAYLOAD_TYPE", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CHALLENGE_REPLY_ERROR_TYPE__CHALLENGE_REPLY_ERROR_WRONG_PAYLOAD_TYPE", 3 },
  { "CHALLENGE_REPLY_ERROR_NO_PAYLOAD", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CHALLENGE_REPLY_ERROR_TYPE__CHALLENGE_REPLY_ERROR_NO_PAYLOAD", 4 },
  { "CHALLENGE_REPLY_ERROR_PAYLOAD_PARSING_FAILED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CHALLENGE_REPLY_ERROR_TYPE__CHALLENGE_REPLY_ERROR_PAYLOAD_PARSING_FAILED", 5 },
  { "CHALLENGE_REPLY_ERROR_MESSAGE_ERROR", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CHALLENGE_REPLY_ERROR_TYPE__CHALLENGE_REPLY_ERROR_MESSAGE_ERROR", 6 },
  { "CHALLENGE_REPLY_ERROR_NO_RESPONSE", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CHALLENGE_REPLY_ERROR_TYPE__CHALLENGE_REPLY_ERROR_NO_RESPONSE", 7 },
  { "CHALLENGE_REPLY_ERROR_FINGERPRINT_NOT_FOUND", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CHALLENGE_REPLY_ERROR_TYPE__CHALLENGE_REPLY_ERROR_FINGERPRINT_NOT_FOUND", 8 },
  { "CHALLENGE_REPLY_ERROR_CERT_PARSING_FAILED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CHALLENGE_REPLY_ERROR_TYPE__CHALLENGE_REPLY_ERROR_CERT_PARSING_FAILED", 9 },
  { "CHALLENGE_REPLY_ERROR_CERT_NOT_SIGNED_BY_TRUSTED_CA", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CHALLENGE_REPLY_ERROR_TYPE__CHALLENGE_REPLY_ERROR_CERT_NOT_SIGNED_BY_TRUSTED_CA", 10 },
  { "CHALLENGE_REPLY_ERROR_CANNOT_EXTRACT_PUBLIC_KEY", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CHALLENGE_REPLY_ERROR_TYPE__CHALLENGE_REPLY_ERROR_CANNOT_EXTRACT_PUBLIC_KEY", 11 },
  { "CHALLENGE_REPLY_ERROR_SIGNED_BLOBS_MISMATCH", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CHALLENGE_REPLY_ERROR_TYPE__CHALLENGE_REPLY_ERROR_SIGNED_BLOBS_MISMATCH", 12 },
  { "CHALLENGE_REPLY_ERROR_TLS_CERT_VALIDITY_PERIOD_TOO_LONG", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CHALLENGE_REPLY_ERROR_TYPE__CHALLENGE_REPLY_ERROR_TLS_CERT_VALIDITY_PERIOD_TOO_LONG", 13 },
  { "CHALLENGE_REPLY_ERROR_TLS_CERT_VALID_START_DATE_IN_FUTURE", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CHALLENGE_REPLY_ERROR_TYPE__CHALLENGE_REPLY_ERROR_TLS_CERT_VALID_START_DATE_IN_FUTURE", 14 },
  { "CHALLENGE_REPLY_ERROR_TLS_CERT_EXPIRED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CHALLENGE_REPLY_ERROR_TYPE__CHALLENGE_REPLY_ERROR_TLS_CERT_EXPIRED", 15 },
  { "CHALLENGE_REPLY_ERROR_CRL_INVALID", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CHALLENGE_REPLY_ERROR_TYPE__CHALLENGE_REPLY_ERROR_CRL_INVALID", 16 },
  { "CHALLENGE_REPLY_ERROR_CERT_REVOKED", "EXTENSIONS__API__CAST_CHANNEL__PROTO__CHALLENGE_REPLY_ERROR_TYPE__CHALLENGE_REPLY_ERROR_CERT_REVOKED", 17 },
};
static const ProtobufCIntRange extensions__api__cast_channel__proto__challenge_reply_error_type__value_ranges[] = {
{1, 0},{0, 17}
};
static const ProtobufCEnumValueIndex extensions__api__cast_channel__proto__challenge_reply_error_type__enum_values_by_name[17] =
{
  { "CHALLENGE_REPLY_ERROR_CANNOT_EXTRACT_PUBLIC_KEY", 10 },
  { "CHALLENGE_REPLY_ERROR_CERT_NOT_SIGNED_BY_TRUSTED_CA", 9 },
  { "CHALLENGE_REPLY_ERROR_CERT_PARSING_FAILED", 8 },
  { "CHALLENGE_REPLY_ERROR_CERT_REVOKED", 16 },
  { "CHALLENGE_REPLY_ERROR_CRL_INVALID", 15 },
  { "CHALLENGE_REPLY_ERROR_FINGERPRINT_NOT_FOUND", 7 },
  { "CHALLENGE_REPLY_ERROR_MESSAGE_ERROR", 5 },
  { "CHALLENGE_REPLY_ERROR_NONE", 0 },
  { "CHALLENGE_REPLY_ERROR_NO_PAYLOAD", 3 },
  { "CHALLENGE_REPLY_ERROR_NO_RESPONSE", 6 },
  { "CHALLENGE_REPLY_ERROR_PAYLOAD_PARSING_FAILED", 4 },
  { "CHALLENGE_REPLY_ERROR_PEER_CERT_EMPTY", 1 },
  { "CHALLENGE_REPLY_ERROR_SIGNED_BLOBS_MISMATCH", 11 },
  { "CHALLENGE_REPLY_ERROR_TLS_CERT_EXPIRED", 14 },
  { "CHALLENGE_REPLY_ERROR_TLS_CERT_VALIDITY_PERIOD_TOO_LONG", 12 },
  { "CHALLENGE_REPLY_ERROR_TLS_CERT_VALID_START_DATE_IN_FUTURE", 13 },
  { "CHALLENGE_REPLY_ERROR_WRONG_PAYLOAD_TYPE", 2 },
};
const ProtobufCEnumDescriptor extensions__api__cast_channel__proto__challenge_reply_error_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "extensions.api.cast_channel.proto.ChallengeReplyErrorType",
  "ChallengeReplyErrorType",
  "Extensions__Api__CastChannel__Proto__ChallengeReplyErrorType",
  "extensions.api.cast_channel.proto",
  17,
  extensions__api__cast_channel__proto__challenge_reply_error_type__enum_values_by_number,
  17,
  extensions__api__cast_channel__proto__challenge_reply_error_type__enum_values_by_name,
  1,
  extensions__api__cast_channel__proto__challenge_reply_error_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
