name: Build ESP-IDF Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up ESP-IDF
      run: |
        sudo apt-get update
        sudo apt-get install git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
        git clone --recursive https://github.com/espressif/esp-idf.git esp-idf
        cd esp-idf
        git checkout v5.1.2  # or whichever version you want
        ./install.sh all
        echo "source $GITHUB_WORKSPACE/esp-idf/export.sh" >> $GITHUB_ENV

    - name: Build project
      run: |
        source $GITHUB_WORKSPACE/esp-idf/export.sh
        idf.py build
